### ISSUE TITLE
Failing migration with existing apps

### ISSUE THREAD

**Issue by SebastianKapunkt** [codingjoe/django-mail-auth#3]
**Problem:**
When running the migration the migration will fail with this error:
````
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration app_name.0002_auto_XXXX is applied before its dependency mailauth_user.0001_initial on database 'default'.
````

**Guess**
its happening because an existing app is referencing in a migration the ```to=settings.AUTH_USER_MODEL``` and therefore the non existing user migration.

**Expected behaviour**
The migration should always run no matter what exists before.

**My Workaround**
I just delete ```AUTH_USER_MODEL = 'mailauth_user.EmailUser'``` for the duration of the migration

**Comment by codingjoe** [comment]
@SebastianKapunkt that is a good question. In Django the order in which applications are listed in the `INSTALLED_APPS` setting matters. This is even truer for the user model, since it's swappable. 
Usually in migration you have dependencies listed. With swappable models, that does not really work, since you an application doesn't know what a migration might depend on.

Therefore, I'd recommend the following order:
```
INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',

    'mailauth.contrib.user',

    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',
]
```

Let me know if you have further questions. I am happy to help.

Best
-Joe
